import requests
url = "http://localhost:8000/notes/"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQiIsImV4cCI6MTc1Mjc3MTM5Mn0.vlz6cvEM645IVCKhAw-iYL2N-aokNbrH6lBnplr2JbQ"  # Замените на ваш реальный JWT токен

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

for i in range(1, 101):
    data = {
        "text": f"Note {i} - autogenerated for UserB"
    }
    response = requests.post(url, json=data, headers=headers)
    print(f"Note {i}: {response.status_code} - {response.json() if response.status_code != 201 else 'Created'}")