version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/user
      SECRET_KEY: your_secret_key
      REDIS_URL: redis://redis:6379
      CACHE_TTL: 300
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  celery-worker:
    build: .
    command: celery -A celery_app.celery worker --loglevel=info
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: 